### ISSUE TITLE
Secure Websocket support

### ISSUE THREAD

**Issue by D4nte** [status-im/go-waku#21]
We currently use a [go-waku instance](https://github.com/status-im/js-waku/blob/00d4c41967e01ea05ccf2b136e10b5bb2131cbdb/web-chat/src/App.tsx#L38) as a gateway to the waku test fleet in the [js-waku web app](https://status-im.github.io/js-waku/).

After further [investigation](https://github.com/status-im/js-waku/issues/50#issuecomment-825396910), we can confirm that, regarding the support of insecure websocket `ws` in a secure web page `https`:
	- Firefox supports it only if some advance security parameters are modified using `about:config`.
	- Chrome does not support it at all.

This means that js-waku [must support wss](https://github.com/status-im/js-waku/issues/50) to be relevant.

Also, go-waku being able to listen on a secure websocket `wss` would allow a smooth experience for web app demo and also testing of `wss` (as nim-waku does not yet support websockets).

@richard-ramos can you please consider adding support?

**Comment by richard-ramos** [comment]
Since there's no support out of the box for listening / dialing wss multiaddresses (see: https://github.com/libp2p/go-ws-transport/issues/70), I setup a reverse proxy with nginx that uses a self signed certificate to add secure websockets support.

To test, you can use /ip4/134.209.113.86/tcp/443/wss/p2p/16Uiu2HAmVVi6Q4j7MAKVibquW8aA27UNrA4Q8Wkz9EetGViu8ZF1

**Comment by richard-ramos** [comment]
The config used for nginx in my DO droplet can be seen here: https://gist.github.com/richard-ramos/63eadded212aaa994216f98583acc257

**Comment by richard-ramos** [comment]
Closing this issue, as WSS listening support can be achieved with nginx, and dialing WSS nodes is not required at the moment.
